### ISSUE TITLE
It takes a lot of time to generate/load worlds

### ISSUE THREAD

**Issue by TheViictor** [MCMrARM/toolbox-issue-tracker#1]
Please fill out the information below before hitting submit!

### Details

***What did you expect to happen?***

To open a world normall. 

***What happened?***

It took almost one minute to generate the world.

***When does this happen?***

When creating a world or entering one.

### Mods/Texture Packs

What mods and or texture packs do you have installed?

Any

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: *Samsung Galaxy Tab 4 (SM-T530)*

Android version: *Android 5.1.1*

Architecture: *Idk :P*

MC:PE version: *0.15.1.2*

**Comment by sliceofcode** [comment]
While @MCMrARM is aware of the issue, he can't seem to find out why it occurs.

**Comment by sliceofcode** [comment]
Update: This has something to do with Realms. Try removing `options.txt`, or remove all Realms data.

**Comment by MCMrARM** [comment]
Fixed this issue for beta 3 which will be out soon.
