### ISSUE TITLE
Crafting Table

### ISSUE THREAD

**Issue by Head678** [MCMrARM/toolbox-issue-tracker#11]
Please fill out the information below before hitting submit!

### Details

***What did you expect to happen?***
Clicking on the crafting table block makes toolbox crash

...

***What happened?***

...

***When does this happen?***

... Everytime

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- ...
- ...None
- ...

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: *Device model here. (Samsung S6? Oneplus 3?)*
Saumung Prevail Lte
Android version: *Android verison here. (Lollipop? KitKat?)*
Android 4.4 KitKat
Architecture: *ARM or x86*
x86
MC:PE version: *0.XX.XX*
0.15.1.2

**Comment by MCMrARM** [comment]
I can not reproduce it. Could you try to provide me stacktrace?

**Comment by Head678** [comment]
It does not crash anymore Thank You
