### ISSUE TITLE
Toolbox add

### ISSUE THREAD

**Issue by Alibaykus** [MCMrARM/toolbox-issue-tracker#12]
Mr arm please add bugkit pixaxe

### Details

***What did you expect to happen?***

...

***What happened?***

...

***When does this happen?***

...

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- no
- ...
- ...

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: *Device model here. (Asus t00j and arm tablet

Android version: *Android verison here. Lolipop and kitkat

Architecture: x86 or arm

MC:PE version: *0.15.1.2

**Comment by sliceofcode** [comment]
Please be clear on your issue, we cannot understand.
