### ISSUE TITLE
Creating more blocks with same id dosen't work

### ISSUE THREAD

**Issue by PatrikXop** [MCMrARM/toolbox-issue-tracker#13]
Creating more blocks with same id but difrent subValue results creating only 1 block `
Block.defineBlock(249, "Normal_world_ores", [
        ["OreCopper", 0],
        ["OreCopper", 0],
        ["OreCopper", 0],
        ["OreCopper", 0],
        ["OreCopper", 0],
        ["OreCopper", 0], //end of copper(sub0)
        ["OreLead", 0],
        ["OreLead", 0],
        ["OreLead", 0],
        ["OreLead", 0],
        ["OreLead", 0],
        ["OreLead", 0], //end of lead(sub1)
        ["OreAluminum", 0],
        ["OreAluminum", 0],
        ["OreAluminum", 0],
        ["OreAluminum", 0],
        ["OreAluminum", 0],
        ["OreAluminum", 0], //end of aluminum(sub2)
        ["OreNickel", 0],
        ["OreNickel", 0],
        ["OreNickel", 0],
        ["OreNickel", 0],
        ["OreNickel", 0],
        ["OreNickel", 0], //end of nicle(sub3)
        ["OrePlatinum", 0],
        ["OrePlatinum", 0],
        ["OrePlatinum", 0],
        ["OrePlatinum", 0],
        ["OrePlatinum", 0],
        ["OrePlatinum", 0], //end of platinum(sub4)
        ["OreSilver", 0],
        ["OreSilver", 0],
        ["OreSilver", 0],
        ["OreSilver", 0],
        ["OreSilver", 0],
        ["OreSilver", 0], //end of silver(sub5)
        ["OreTin", 0],
        ["OreTin", 0],
        ["OreTin", 0],
        ["OreTin", 0],
        ["OreTin", 0],
        ["OreTin", 0], //end of tin 6
        ["OreStibnite", 0],
        ["OreStibnite", 0],
        ["OreStibnite", 0],
        ["OreStibnite", 0],
        ["OreStibnite", 0],
        ["OreStibnite", 0], //end of OreStibnite sub 7
        ["OreBauxite", 0],
        ["OreBauxite", 0],
        ["OreBauxite", 0],
        ["OreBauxite", 0],
        ["OreBauxite", 0],
        ["OreBauxite", 0], //end of OreBauxite sub 8
        ["OreBeryllium", 0],
        ["OreBeryllium", 0],
        ["OreBeryllium", 0],
        ["OreBeryllium", 0],
        ["OreBeryllium", 0],
        ["OreBeryllium", 0], //end of OreBeryllium sub 9
        ["OreChromite", 0],
        ["OreChromite", 0],
        ["OreChromite", 0],
        ["OreChromite", 0],
        ["OreChromite", 0],
        ["OreChromite", 0], //end of OreChromite sub 10
        ["LithiumOre", 0],
        ["LithiumOre", 0],
        ["LithiumOre", 0],
        ["LithiumOre", 0],
        ["LithiumOre", 0],
        ["LithiumOre", 0], //end of LithiumOre sub 11
        //####radioactive!####
        ["OreUranium", 0],
        ["OreUranium", 0],
        ["OreUranium", 0],
        ["OreUranium", 0],
        ["OreUranium", 0],
        ["OreUranium", 0], //end of LithiumOre sub 12
        ["OrePotassium", 0],
        ["OrePotassium", 0],
        ["OrePotassium", 0],
        ["OrePotassium", 0],
        ["OrePotassium", 0],
        ["OrePotassium", 0], //end of LithiumOre sub 13
        ["OreThorium", 0],
        ["OreThorium", 0],
        ["OreThorium", 0],
        ["OreThorium", 0],
        ["OreThorium", 0],
        ["OreThorium", 0], //end of LithiumOre sub 14
        ["OreLutetium", 0],
        ["OreLutetium", 0],
        ["OreLutetium", 0],
        ["OreLutetium", 0],
        ["OreLutetium", 0],
        ["OreLutetium", 0] //end of LithiumOre sub 15
    ],
    1, 1, true);`

texturpack - i checked names in texturpack and in mod 3 times
-each png is 16x16

### Device Information

Model: *Device model here: Samsung Galaxy A5 2016

Android version: 5.1.1  - A510FXXU2APC4

Architecture: ARM Cortex-A53

MC:PE version: *0.15.1*

**Comment by PatrikXop** [comment]
full code can be finde on: https://github.com/PatrikXop/Great-Tech/blob/master/Great%20Tech.js

**Comment by MCMrARM** [comment]
I don't think it could work on Beta 3, there was no code for that. Also, I confirm the issue. As a workaround you can create textures using the id in texture name (eg. customore_0.png, customore_1.png in images/items-opaque folder) as that should get used as the data value. Then you can just define the block as Block.defineBlock(249, "Normal_world_ores", "customore");

**Comment by MCMrARM** [comment]
Fixed, queued for the next beta build for 0.15.2.
