### ISSUE TITLE
ModPe.langEdit() dose not work

### ISSUE THREAD

**Issue by PatrikXop** [MCMrARM/toolbox-issue-tracker#14]
in code: wich can be finde on: 
> https://github.com/PatrikXop/Great-Tech/blob/master/Great%20Tech.js

renameTick() on line 193; is being initalized inside modTick() on line 166 and it should rename blocks with same id but difrent subValue
since blocks with sub1,sub2.. dont work( > https://github.com/MCMrARM/toolbox-issue-tracker/issues/13 ) i expected it to happen with at least block with sub_0 but it dosent happen for it. I also created seperated mod with only 1 block and renameTick() initalize in newLevel(), but didn't work.

### Device Information
Model: *Device model here: Samsung Galaxy A5 2016

Android version: 5.1.1 - A510FXXU2APC4

Architecture: ARM Cortex-A53

MC:PE version: 0.15.1

**Comment by MCMrARM** [comment]
Well, this doesn't work this way on Toolbox. The string IDs for modpe block names follow this syntax: tile.modpe.ID.NAME.name (eg. tile.modpe.1.stone.name)

**Comment by MCMrARM** [comment]
If this issue also happens on strings that exist, please reopen the issue.

**Comment by Patr0la** [comment]
Ok, tnx for answering and sorry for my bad eng!
