### ISSUE TITLE
ModPE Server Functions don't work

### ISSUE THREAD

**Issue by LonelyDazab** [MCMrARM/toolbox-issue-tracker#19]
all server functions doesn't work
(Server.getAddress(); usw.)

***What did you expect to happen?***

?? Sry my english is bad.

***What happened?***

It crashd

***When does this happen?***

To day

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- my own mod
- ...
- ...

### Logcat

*No.*

### Device Information

Model: *Device model here. (Lg leon)*

Android version: *Android verison here. (5.0.1)*

Architecture: *ARM or x86*

MC:PE version: *0.15.x*

**Comment by MCMrARM** [comment]
Fixed for the upcoming beta.

**Comment by LonelyDazab** [comment]
Thx
