### ISSUE TITLE
Launcher Options; Closing crashes Toolbox

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#20]
I have already submitted issues about Launcher Options.

This time, when I was importing a mod and activating it, everything was fine, then when I clicked the back button at the corner. It crashed.

MCPE Version: 0.15.1.2
Android Version: 5.0.1
Device Name: Asus ZenPad 10 (P01T)
Device Type: Intel

Between, it crashes, but when I open the app again... The mods is activated, only the crashing is a issue.

![image](https://cloud.githubusercontent.com/assets/9281684/16798869/66acf884-48ee-11e6-92d8-988ec3b8f446.png)

EDIT: This is very annoying please fix it!!!

**Comment by Smasher535** [comment]
![screenshot_2016-07-02-11-34-42](https://cloud.githubusercontent.com/assets/9281684/16712824/eaabe8d8-4692-11e6-84dc-f9ab5699fd29.jpg)

**Comment by TheBigHacker0100** [comment]
THAT HAPPENS TO ME TOO PLEASE FIX IT! I HAVE EXACTLY SAME PROBLEM!! ANDROID 5.0.1

**Comment by Blakintosh** [comment]
Yeah, I have this, but if you go out of ModPE and tap on General for example it restarts as it should

**Comment by ghost** [comment]
I got a tablet, its not like mobile version, your trick doesn't work :-(

**Comment by ghost** [comment]
This got fixed for me :D 👍
