### ISSUE TITLE
Server.sendChat() doesn't work, custom throwables are not supported

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#21]
In the BlockLauncher you could execute the function Server.sendChat("hello"); as net.zhuoweizhang.mcpelauncher.ScriptManager.sendChat("hello"); because of the Server.sendChat doesn't work in servers.

I tried with io.mrarm.mctoolbox.ScriptManager.sendChat("hello"); but it said that 'io' is not defined please give me the solution for that function.

---
## OTHER QUESTIONS 

How do I create custom throwables?
How do I write/edit a file using ModPE

**Comment by MCMrARM** [comment]
Both Server.sendChat() and custom throwables have been now implemented and will be available in the next beta.

**Comment by ghost** [comment]
Ok
