### ISSUE TITLE
Crashes... Crashes... Crashes...

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#23]
I was playing at play.leet.cc and it just crashes! Crashes in all servers!

First, I was using VertexClientPE and ToolBox crashed again. Then I used my own mod... same thing. Then I used GhostHack and same thing. Please fix it!!

Android Version: 5.0.1
ToolBox version: Latest (from Google play store)
MCPE Version: 0.15.1.2
Device type: Intel

Im getting this when I open the app:
![screenshot_2016-07-02-11-34-42](https://cloud.githubusercontent.com/assets/9281684/16712806/78d80098-4692-11e6-89ab-3ce72e87604b.jpg)

**Comment by slice** [comment]
This is probably due to ModPE incompatibility. Also -- don't hack on servers. Don't be an asshole. Wait for 100% ModPE support.

**Comment by ghost** [comment]
Dont call me that!

**Comment by slice** [comment]
I can say what I want, buddy.
