### ISSUE TITLE
ModPE.setCamera() is buggy

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#25]
### Details

**_What did you expect to happen?**_

I "camera" should view the pig's view (idk how to describe)

**_What happened?**_

The Hand dissappears (Probably it shows now the pigs hand), I still see the world as the player does, the animal (That i wanted to set the canera on) dissappears and dropped items will rotate in a wierd way

**_When does this happen?**_

function attackHook(att,vic){
ModPE.setCamera(vic);
}

Click an animal (I clicked a pig)
### Mods/Texture Packs

function attackHook(att,vic){
ModPE.setCamera(vic);
}
### Logcat

Nope
### Device Information

Model: Sony Xperia Z1 Compact

Android version: 5.1.1

Architecture: ARM

MC:PE version: 0.15.1.2 & 0.14.3

**Comment by Smasher535** [comment]
For your Eaura mod in ServiceHack?

**Comment by Godsoft029** [comment]
1. Servicehack is paused now
2. Wheres the sense???
3. This is the toolbox issue tracker

**Comment by slice** [comment]
@Godsoft029 
1. ???
2. This applies to Toolbox.
3. This applies to Toolbox.

**Comment by ghost** [comment]
Well he deleted his comment. I'll delete mine too

**Comment by MCMrARM** [comment]
I'm pretty sure this got fixed at one point.
