### ISSUE TITLE
Closed (fixed)

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#26]
Closed (fixed)

**Comment by ghost** [comment]
Emmm...

**Comment by slice** [comment]
This is outside the purpose of Toolbox. It isn't meant to unobfuscate ModPE scripts, just like how your toaster isn't supposed to do your laundry.

Even if we wanted to implement such a feature, obfuscation is, well, difficult and very diverse. So sorry, but no.

**Comment by Smasher535** [comment]
NOOOOOOOOOO! ALL MY MODS IS USELESS NOW!!!!
