### ISSUE TITLE
Mob spawning is broken

### ISSUE THREAD

**Issue by theapplelord** [MCMrARM/toolbox-issue-tracker#3]
Please fill out the information below before hitting submit!

### Details

***What did you expect to happen?***

Spawn a mob

***What happened?***

The game crashed

***When does this happen?***

When trying to spawn mob from menu

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- none

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: Samsung Galaxy J5

Android version: Lolipop 5.1

Architecture: *ARM? x86 is not supported.*

MC:PE version: 0.15.1

**Comment by theapplelord** [comment]
There is also no husk and stray and skeleton/zombie horse in the mob spawning menu

**Comment by sliceofcode** [comment]
I can spawn mobs using both eggs and the menu without a crash.

Those eggs are missing from the mob spawning menu though, so for the time being I'll mark this issue as partial until someone can confirm that this is reproducible.

**Comment by sliceofcode** [comment]
Strange enough: For me, I have a blank egg that's called "Spawn" that just crashes the game, but I can spawn any other mob without crashes.

**Comment by MCMrARM** [comment]
Does the Mob Picker menu open for you at all?

**Comment by sliceofcode** [comment]
Can you try providing a logcat?

**Comment by theapplelord** [comment]
The mob picker menu opens but when i tap on the picture of a mob like a zombie it crashes

**Comment by MCMrARM** [comment]
Fixed in final 0.15.1 version.
