### ISSUE TITLE
TB crashes when you're using hand

### ISSUE THREAD

**Issue by 4g0tTeN** [MCMrARM/toolbox-issue-tracker#33]
When I trying to touch blocks with hand toolbox crashes. I have no textures/mods installed

Model: Samsung Galaxy Tab 4.10.1 3G (SM-T531)

Android version: 5.0.2 Lollipop

Architecture: ARMv7

MC:PE version: 0.15.2.1

**Comment by Juze1500** [comment]
Thanks for your crash report. It will be fixed in next WE beta.

**Comment by Juze1500** [comment]
Fixed in 2 WE beta.
