### ISSUE TITLE
Can't import ModPE Script

### ISSUE THREAD

**Issue by Johnmacrocraft** [MCMrARM/toolbox-issue-tracker#34]
When I try to import ModPE Script on latest version (WorldEdit beta, XBL Beta) and previous version it doesn't allow me to import any ModPE Script. Tapping ModPE Script file on file list it doesn't add it to my list. Weird thing is this doesn't happen on previous version (Before versions that I mentioned on the top) allows me to import it.

Device: Samsung Galaxy S3 3G Korea SKTelecom (SHW-M440S)
Android version: Jelly Bean
Toolbox version: Latest version (WorldEdit beta, XBL Beta) and previous version

**Comment by rodrigojxd** [comment]
It also happens to me. I tried to import mods via the Es File Explorer and the CM File Manager but none worked for .js and .modpkg (works well for textures).
Device:  Zenfone 5 (a501cg)
Android version: 6.0.1
Toolbox version: Latest version (Xbox Live beta)

**Comment by TheBigHacker0100** [comment]
That happens to me too, then I used the default file manager and it worked. I have Android 5.0.1

**Comment by rodrigojxd** [comment]
Ohhh!!! I didn't know that there was the option "Show Sd card" in the Import menu. Thank you!

**Comment by Blakintosh** [comment]
Yeah, this is an issue I had. Certain file managers don't import properly, such as Cabinet and the ones you've had issues with. The base Android one works, fortunately and so does FX file manager.

**Comment by Johnmacrocraft** [comment]
@TheBigHacker0100 @Rodrigo294X @Black-DeathPE Hey these 3 guys that successed importing ModPE Script to Toolbox using default file explorer, I don't see any ModPE Script import menu in Application menu when I tap any ModPE Script. How can I import using file explorer?

**Comment by Blakintosh** [comment]
@Johnmacrocraft Tap the + button at the bottom right

**Comment by MCMrARM** [comment]
Fixed, fix will be out in the upcoming beta.

**Comment by Johnmacrocraft** [comment]
@MCMrARM It seems ModPE Script import works again propely, but now texture pack doesn't get import. Also, safe mode like BlockLauncher is required, when mod that you installed makes crash you can't use Toolbox unless you delete data!
