### ISSUE TITLE
//distr crashes toolbox

### ISSUE THREAD

**Issue by bobchernow** [MCMrARM/toolbox-issue-tracker#37]
Please fill out the information below before hitting submit!
### Details

It would either work or say not found

...

Crash

...

**_When does this happen?**_
After submitting command. It waits about 5 seconds and the fc
...
### Mods/Texture Packs

What mods and or texture packs do you have installed?
Just toolbox
- ...
- ...
- ...
### Logcat

_Please provide a logcat if you can._
### Device Information

Model: _Device model here. (Samsung S6? Oneplus 3?)_

Note 5

Android version: _Android version here. (Lollipop? KitKat?)_

6.01
Architecture: _ARM or x86_

MC:PE version: _0.XX.XX_

0.15.21

**Comment by Juze1500** [comment]
Fixed in 2 WE beta
