### ISSUE TITLE
TB Modpkg issue

### ISSUE THREAD

**Issue by Jody24** [MCMrARM/toolbox-issue-tracker#45]
Modpkg texture not working

**_What did you expect to happen?**_

Showing the texture from the modpkg file

**_What happened?**_

Its just blank no texture or anything

**_When does this happen?**_

The 3.2.3 Update for 0.15.4 support
### Mods/Texture Packs

What mods and or texture packs do you have installed?
- My Own mod that i make about one week ago
- manipulator mod

Model: SM-G530H

Android version: KitKat

MC:PE version:0.15.4

**Comment by slice** [comment]
TB does not have Modpkg support.

**Comment by thejaustin** [comment]
modpkg isn't FULLY supported. You can use modpk, but the textures in modpkg files don't work yet. This is a feature we need working in Toolbox.

**Comment by Jody24** [comment]
It worked in the 0.15.3 support that dont have texture packs support

**Comment by slice** [comment]
Relevant: https://github.com/sliceofcode/mpep
