### ISSUE TITLE
Suggestion - Place Block

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#48]
There is ModPE.destroyBlock();
Why not ModPE.placeBlock();?

**Comment by Blakintosh** [comment]
Level.setTile()?

**Comment by TheBigHacker0100** [comment]
setTile does not work in LAN worlds/servers

**Comment by ISAAC300** [comment]
ModPE.handleBuildAction();

**Comment by TheBigHacker0100** [comment]
Does that one work?

**Comment by ghost** [comment]
Nah, no function called handleBuildAction in ModPE

**Comment by slice** [comment]
ModPE is not designed to be used with servers.
