### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SuperCatGaming** [MCMrARM/toolbox-issue-tracker#5]
When I opened Toolbox (beta 3) it gave me a black screen for 30 seconds, then closed. This happens every time I open it.

### Device Information

Model: Amazon Kindle Fire 3rd Gen.

Android version: Fire OS 4.5.5.1

MC:PE version: 0.15.1.2

**Comment by sliceofcode** [comment]
Can you please post a logcat?

**Comment by SuperCatGaming** [comment]
Either I don't know how to do it, or it's not working. I've tried 2 apps and the both show nothing after it crashes. (I know they work, they showed things when I clicked buttons in the app, but after I open toolbox and it crashes, it doesn't show anymore.) Am I doing something wrong?

**Comment by sliceofcode** [comment]
Yes. For this issue to be fixed, we need a Logcat. Try connecting your Android device to your PC and using `adb`.

**Comment by SuperCatGaming** [comment]
Then what? (Do note: I would rather not install anything on my computer, if I have to, I can't provide a logcat, sorry.)

**Comment by SuperCatGaming** [comment]
Also, a kindle technically isn't android, and can't do everything android can.

**Comment by sliceofcode** [comment]
Kindle is running an OS based on Android. And without a logcat, we cannot help you, sorry.

**Comment by SuperCatGaming** [comment]
Found the problem. I had a modpe enabled from 0.14 that was crashing Toolbox, just cleared data and it no longer crashes. =)
