### ISSUE TITLE
Autodisabling!?

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#50]
When I import a new mod and click on the back button, it does not load, then when I check ModPEs it's deactivated, I have to re-activate it and go back, goto ModPEs and go back again until it works please fix this 👍 

Android version: 5.0.1
MCPE version: 0.15.3
Device type: INTEL
Device name: Asus ZenPad 10 (P01T_)

**Comment by TheBigHacker0100** [comment]
Same issue :(

**Comment by ghost** [comment]
This got fixed in 1.0.0.16 (newest tb)
