### ISSUE TITLE
Suggestion - Way to import mods through other apps

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#53]
As we know, there is some apps in google playstore that can import mods to BlockLauncher, it makes a prompt and asks you if you wanna import it. My suggestion is that you should add this to ToolBox too 👍

**Comment by ghost** [comment]
Really... ModPE?

**Comment by slice** [comment]
Yes.

**Comment by TheBigHacker0100** [comment]
What do you mean with 'blocklauncher compat'?

**Comment by slice** [comment]
@TheBigHacker0100 BlockLauncher compatability.

**Comment by ghost** [comment]
This is not about BlockLauncher compatibility.........................

**Comment by MCMrARM** [comment]
This is a duplicate of https://github.com/MCMrARM/toolbox-issue-tracker/issues/38

**Comment by ghost** [comment]
rip
