### ISSUE TITLE
Crashes when i go on it

### ISSUE THREAD

**Issue by DragonZyro123** [MCMrARM/toolbox-issue-tracker#6]
When i tap on Toolbox for minecraft pocket edition it crashes before i could do anything

***What did you expect to happen?***

...

***What happened?***

...

***When does this happen?***

Every single time i go on it!

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- servicehack.js
- ...
- ...

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: Samsung tab 4

Android version: *Android verison here. (Lollipop? KitKat?)*

Architecture: *ARM or x86*

MC:PE version: 0.15.1

**Comment by MCMrARM** [comment]
Reset Toolobox app data or reinstall it.
