### ISSUE TITLE
Worldedit doesn't work at the height above 128 blocks.

### ISSUE THREAD

**Issue by Aphys122** [MCMrARM/toolbox-issue-tracker#61]
Please fill out the information below before hitting submit!

### Details

***What did you expect to happen?***

Working worldedit commands at the height above 128 blocks in minecraft pe 1.0.0

***What happened?***

There are no blocks at the height above 128 blocks after pasting block structure or using command //stack

***When does this happen?***

...

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- ...
- ...
- ...

### Logcat

*Please provide a logcat if you can.*

### Device Information

Model: Samsung S3 GT-I9300I

Android version: Kitkat 4.4.4

Architecture: ARM

MC:PE version: 1.0.0.16

**Comment by slice** [comment]
@MCMrARM This looks like a simple fix.

**Comment by MCMrARM** [comment]
Fixed.
