### ISSUE TITLE
Settings getting reseted

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#65]
Everytime I open Toolbox all my settings are gone :( 
This happens to everyone, I have contacted some friends on Twitter and looked at the reviews.
First time I open the update ALL my worlds and servers are gone.. but they are still in /games/com.mojang

Help help help help

**Comment by ghost** [comment]
Mcpe 1.0.6
Tb 3.2.25

**Comment by ghost** [comment]
@MCMrARM up

**Comment by jyyyyylim** [comment]
same, its as if toolbox doesnt read the game saves

**Comment by MCMrARM** [comment]
Is this still an issue?

**Comment by MCMrARM** [comment]
Please note it is impossible for me to read the game's servers from the game internal data directory, but it should still save within Toolbox itself.

**Comment by SuperOP535** [comment]
i use external it should get from games folder like it did in older versions

**Comment by SuperOP535** [comment]
btw this is my new account

**Comment by Johnmacrocraft** [comment]
@SuperOP535 Minecraft doesn't use games folder for settings anymore. Even you set it to External, it only gets stuffs like resource packs from it.
