### ISSUE TITLE
Launcher options does not open

### ISSUE THREAD

**Issue by Rodrigo294X** [MCMrARM/toolbox-issue-tracker#7]
### Details

***What did you expect to happen?***

When I click on the "Launcher Options" button should open the options menu.

***What happened?***

The menu does not open

### Mods/Texture Packs

What mods and or texture packs do you have installed?

- None

### Device Information

Model: *Asus Zenfone 5 Android 6.0.1*

Architecture: *x86*

MC:PE version: *0.15.1.2*

**Comment by sliceofcode** [comment]
Can you please provide a logcat?

**Comment by Rodrigo294X** [comment]
Logcat : https://www.dropbox.com/s/rpur5mubbu5q5lv/logcat.txt?dl=0

**Comment by sliceofcode** [comment]
Ping @MCMrARM

**Comment by MCMrARM** [comment]
I am looking into this

**Comment by Rodrigo294X** [comment]
I do not know the reason but it's working now . I'm confused.

**Comment by MCMrARM** [comment]
It has been fixed in the Google Play edition.

**Comment by Rodrigo294X** [comment]
Oh. It has been updated automatically and I did not realize. Thank you!
