### ISSUE TITLE
Crash when rendering custom textured item

### ISSUE THREAD

**Issue by Godsoft029** [MCMrARM/toolbox-issue-tracker#8]
### Details

***What did you expect to happen?***

Render the item correctly (Custom texture)

***What happened?***

Crash
(The Item icon is blank in the inventory)

***When does this happen?***

I click on the item in the inventory and before the hand got rendered/appeared on the screen, the game crashes/kicks me out.

### Mods/Texture Packs

What mods and or texture packs do you have installed?
Pack:
https://www.sendspace.com/file/e2z5qb

Code:
ModPE.setItem(499, "p2000", 0, "TestGun", 1);

### Logcat

http://pastebin.com/ApEghv42

### Device Information

Model: D5503 (Sony Xperia Z1 Compact)

Android version: 5.1.1

Architecture: ARM

MC:PE version:.0.15.1.2

MC:PE Version Checksum: 0a0325cf5ad65d920043f0d6ce9dae8f

**Comment by MCMrARM** [comment]
Custom textured items are not supported currently.

**Comment by Godsoft029** [comment]
Good luck at fixing it :)

**Comment by Juze1500** [comment]
Fixed it.

**Comment by MCMrARM** [comment]
Fixed for final 0.15.1 update.
