### ISSUE TITLE
Toolbox no longer works properly on 0.15.1.2, Launcher Options does not work

### ISSUE THREAD

**Issue by Smasher535** [MCMrARM/toolbox-issue-tracker#9]
When I open the app it tells me that the Minecraft PE version is unsupported, then when I try to click on Launcher Options nothing happens!!!!

![screenshot_2016-07-02-11-34-42](https://cloud.githubusercontent.com/assets/9281684/16546821/453dc55a-4157-11e6-83f7-645330040fb4.jpg)

I have an Android 5.0.1
My Minecraft PE version is 0.15.1.2
I have a Intel device, BlockLauncher and Toolbox worked perfectly in 0.14.x

**Comment by sliceofcode** [comment]
This probably means that your architecture is not supported. x86 support was added a few days ago so I'm guessing it isn't very stable. @MCMrARM

**Comment by Smasher535** [comment]
Asus Zenpad 10 (P01T)
Android 5.0.1
Intel Processor

**Comment by MCMrARM** [comment]
Fixed in final 0.15.1 version.
